###
### Criar usuário
###

POST http://localhost:7070/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@example.com.br",
  "password": "password123",
  "cpf": "22765632039",
  "isAdmin": false
}

###
### Fazer login
###
POST http://localhost:7070/login
Content-Type: application/json

{
  "password": "password123",
  "cpf": "30765632039"
}

###
### Get all users
###
GET http://localhost:7070/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTcxMDg0MTQsImlzQWRtaW4iOnRydWUsInVzZXJJZCI6IjcxMGNjNTQ1LWM3OGQtNDU1Yi04NjAyLTA4MGMyODNjMTU5OCJ9.E8K8Az9IiP93W3Prdad7Nm4QpATz7VktCCCjY2LGPEw

###
### Get user info
###
GET http://localhost:7070/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTcxMDg0MTQsImlzQWRtaW4iOnRydWUsInVzZXJJZCI6IjcxMGNjNTQ1LWM3OGQtNDU1Yi04NjAyLTA4MGMyODNjMTU5OCJ9.E8K8Az9IiP93W3Prdad7Nm4QpATz7VktCCCjY2LGPEw
