apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: LoadBalancer
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7070
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: gustavogcosta/tc-auth:v1
          env:
            - name: DB_USER
              value: 'docker'
            - name: DB_PASSWORD
              value: 'docker'
            - name: DB_HOST
              value: 'mysql-service'
            - name: DB_PORT
              value: '3306'
            - name: DB_NAME
              value: 'docker'
          ports:
            - containerPort: 7070
