apiVersion: v1
kind: Service
metadata:
  name: catalog-service
spec:
  type: LoadBalancer
  selector:
    app: catalog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
        - name: catalog
          image: gustavogcosta/tc-catalog:latest
          env:
            - name: SPRING_DATASOURCE_URL
              value: 'jdbc:mysql://mysql-service/docker?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC'
            - name: SPRING_DATASOURCE_USERNAME
              value: 'docker'
            - name: SPRING_DATASOURCE_PASSWORD
              value: 'docker'
          ports:
            - containerPort: 8082
