apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: catalog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
        - name: catalog
          image: gustavogcosta/tc-catalog:latest
          env:
            - name: SPRING_DATASOURCE_URL
              value: 'jdbc:mysql://mysql-service/docker?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC'
            - name: SPRING_DATASOURCE_USERNAME
              value: 'docker'
            - name: SPRING_DATASOURCE_PASSWORD
              value: 'docker'
            - name: SPRING_SERVLET_HEADERS_STRICT_TRANSPORT_SECURITY_PRELOAD
              value: 'true'
            - name: SPRING_SERVLET_HEADERS_STRICT_TRANSPORT_SECURITY_MAX_AGE
              value: '31536000'
            - name: SPRING_SERVLET_HEADERS_STRICT_TRANSPORT_SECURITY_INCLUDE_SUBDOMAINS
              value: 'true'
            - name: SPRING_CONTENT_TYPE_OPTIONS
              value: 'nosniff'
            - name: SPRING_SERVLET_HEADERS_CONTENT_SECURITY_POLICY
              value: "default-src 'self'"
            - name: SPRING_SERVLET_HEADERS_XSS_PROTECTION
              value: "1; mode=block"
            - name: SPRING_SERVLET_HEADERS_FRAME_OPTIONS
              value: "DENY"
            - name: SPRING_SERVLET_HEADERS_CACHE_CONTROL
              value: "no-cache, no-store, must-revalidate"
          ports:
            - containerPort: 8082
