apiVersion: apps/v1
kind: Deployment
metadata:
  name: notify-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notify
  template:
    metadata:
      labels:
        app: notify
    spec:
      containers:
        - name: notify
          image: gustavogcosta/tc-notify:latest
          env:
            - name: ORDER_URL
              value: "order-service"
            - name: RABBITMQ_HOSTNAME
              value: "rabbitmq-service"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
              value: "admin"
            - name: RABBITMQ_PASSWORD
              value: "admin"
          ports:
            - containerPort: 3000