server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://192.168.49.2:31305/docker?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: docker
    password: docker

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect